#Zadawanie pytań
#wyświetlenie zapytania, oraz nie przejście do nowej lini, a pozostanie 
print("Ile masz lat?", end=' ')
age = input()
print("Ile masz wzrostu?", end=' ')
height = input()
print("Ile ważysz?", end=' ')
weight = input()
print("Jaki napój lubisz pić?")
drink = input()
print("Jak jest twoj ulubiony kolor?")
kolor = input()
print("Masz ",age+" lat.")
print(f"A więc masz {age} lat, {height} wzrostu i ważysz {weight}.")
print(f"Lubisz pić {drink}")
print(f"Twój ulubiony kolor to {kolor}")
print("Podaj liczbę")
x = int(input())
print(f"{x}+2={x+2}, :)")
